import grpc
import argparse
import sys

#Modules generated by protoc
import service_pb2
import service_pb2_grpc

def get_status_name(status_code):
    return service_pb2.Status.Name(status_code)

def get_action_name(action_code):
    return service_pb2.ActionState.Name(action_code)

def run():

    #Register arguments for CLI -----------------------
    parser = argparse.ArgumentParser(description="Fleet Management CLI")
    subparsers = parser.add_subparsers(dest="command", help="Commands")

    #Commands:
    #Register
    reg = subparsers.add_parser("register", help="Register a new Device") #TODO: remove hardcoden command name
    reg.add_argument("--id", required=True, help="Device Id")

    #info
    info = subparsers.add_parser("info", help="Get device info") #TODO: remove hardcoden command name
    info.add_argument("--id", required=True, help="Device id")

    #Update
    update = subparsers.add_parser("update", help="Software update") #TODO: remove hardcoden command name
    update.add_argument("--id", required=True, help="Device id")
    update.add_argument("--ver", default="1.0.0", help="Software version") #Todo: remove hardcoded value

    #Track Action
    track = subparsers.add_parser("track", help="Check action status") #TODO: remove hardcoden command name
    track.add_argument("--action_id", required=True, help="Action Id")

    args = parser.parse_args()
    #--------------------------------------------------

    #Connect to server
    with grpc.insecure_channel("localhost:50051") as channel: #TODO: remove hardcoded port
        stub = service_pb2_grpc.DeviceManagerStub(channel)

        #TODO: remove hardcoded string commands
        try:
            if args.command == "register":
                resp = stub.RegisterDevice(service_pb2.RegisterRequest(
                    device_id=args.id, initial_status=service_pb2.IDLE))
                print(f"Registered: {resp.device_id} Status: {get_status_name(resp.status)}")
            elif args.command == "info":
                resp = stub.GetDeviceInfo(service_pb2.InfoRequest(device_id=args.id))
                print(f"Device: {resp.device_id} Current Status: {get_status_name(resp.status)}")
            elif args.command == "update":
                resp = stub.InitiateDeviceAction(service_pb2.ActionRequest(
                    device_id=args.id, action_type="SOFTWARE_UPDATE", version=args.ver))
                print(f"Updating device, Action ID: {resp.action_id}. Change state to UPDATING")
            elif args.command == "track":
                resp = stub.GetActionStatus(service_pb2.ActionStatusRequest(action_id=args.action_id))
                print(f"Action: {args.action_id} State: {get_action_name(resp.state)}")
            else:
                parser.print_help()
        except grpc.RpcError as e:
            print(f"Error: {e.details()}")

if __name__ == '__main__':
    run()